# Server settings
server.port=8080

# MongoDB settings
spring.data.mongodb.uri=mongodb://localhost:27017/bi_platform

# File Upload properties
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Mock Mail properties (avoids startup crashes)
spring.mail.host=localhost
spring.mail.port=25
spring.mail.username=user@example.com
spring.mail.password=password
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
